import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MastHeader from '../components/common/mastHeader/MastHeader';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Johnny Ray Alt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MastHeader />

      <main className={styles.main}>
        <h1>Some cool shit will go here</h1>
      </main>
    </div>
  )
}

export default Home
